name: Build Control D AI Malware Blocklist
#run-name:
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Provide Git identity
        run: |
          git config user.email ${{ vars.GIT_EMAIL }}
          git config user.name ${{ vars.GIT_USERNAME }}
  
      - name: Download Tranco TOP1M
        run: |
          wget https://tranco-list.eu/top-1m.csv.zip
          unzip top-1m.csv.zip
          
      - name: Download DomCop TOP10M
        run: |
          wget https://www.domcop.com/files/top/top10milliondomains.csv.zip
          unzip top10milliondomains.csv.zip
          
      - name: Format and merge lists
        run: |
          # Remove first 1000 domains
          tail -n +1001 top-1m.csv \
            # Output domain column
            | cut -d ',' -f 2 \
            # Remove carriage return/CRLF
            | sed 's/\r//' > top-1m.txt
          
          # Remove header and first 1000 domains
          tail -n +1002 top10milliondomains.csv \
            | cut -d ',' -f 2 \
            # Remove double quotes
            | awk '{gsub(/"/ ,""); print}' > top10milliondomains.txt
            
          cat top-1m.txt top10milliondomains.txt \
            # Filter out .gov and .edu TLDs
            | grep -vE '\.(gov|edu)(\.[a-z]{2})?$' \
            # Remove www subdomain
            | awk '{sub("^www\\." ,""); print}' \
            | sort -u -o input.txt
          
          wc -l top-1m.txt
          wc -l top10milliondomains.txt
          wc -l input.txt
          
          
      
        
          

          
          
          
