name: Build
#run-name:
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Install and configure NextDNS
        run: |
          bash install_nextdns.sh ${{ secrets.NEXTDNS_PROFILE_ID }}
          curl ${{ secrets.NEXTDNS_LINK_IP }}
          
      - run: |
          dig @${{ vars.NEXTDNS_DNS1 }} brave.com
