name: Test Workflow
#run-name:
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: |
          bash workflow_scripts/control_d_installer.sh -s 1c0lkqpn4zg forced
          dig @1c0lkqpn4zg.dns.controld.com google.com
