name: Test Workflow
#run-name:
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "VARIABLE=greeen" >> "$GITHUB_ENV"
      - run: echo "${{ env.VARIABLE }}"
    
