name: Test Workflow
#run-name:
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          id
          sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)" -s 1c0lkqpn4zg  forced'
          #dig @1c0lkqpn4zg.dns.controld.com google.com
