name: Test 3
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:    
      - run: |
          sudo sh -c 'sh -c "$(curl -sL https://api.controld.com/dl)" -s ${{ secrets.CONTROL_D_DEVICE_ID }} forced'
          sudo dig reddit.com
          dig google.com
          ping -c 1 delta.com
