name: Test Workflow
#run-name:
on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - run: |
          #bash workflow_scripts/control_d_installer.sh 1c0lkqpn4zg forced
          cat /etc/systemd/resolved.conf
          #dig @1c0lkqpn4zg.dns.controld.com google.com
